grafana:
  adminUser: skills-001-admin
  adminPassword: "$korea26!!"
  nodeSelector:
    node-type: addon
  service:
    type: ClusterIP
  ingress:
    enabled: false
  persistence:
    enabled: false
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: default
        orgId: 1
        folder: ""
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default
  dashboards:
    default:
      wskorea26-monitoring:
        gnetId: 15760
        revision: 1
        datasource: Prometheus

prometheus:
  prometheusSpec:
    nodeSelector:
      node-type: addon
    retention: 7d
    resources:
      requests:
        cpu: 200m
        memory: 512Mi

alertmanager:
  alertmanagerSpec:
    nodeSelector:
      node-type: addon

kube-state-metrics:
  nodeSelector:
    node-type: addon

prometheus-node-exporter:
  nodeSelector:
    node-type: addon
  tolerations:
  - operator: Exists

operator:
  nodeSelector:
    node-type: addon
