apiVersion: v1
kind: Namespace
metadata:
  name: app
  labels:
    app.kubernetes.io/part-of: apdev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-sa
  namespace: app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: product-sa
  namespace: app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stress-sa
  namespace: app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: db-init-sa
  namespace: app
